const ACTION_TYPES = {

  CLEAR_TASK_ERROR: 'CLEAR_TASK_ERROR',
  CLEAR_USER_ERROR: 'CLEAR_USER_ERROR',
 
  
  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',

  CREATE_USER_TASK_REQUEST: 'CREATE_USER_TASK_REQUEST',
  CREATE_USER_TASK_SUCCESS: 'CREATE_USER_TASK_SUCCESS',
  CREATE_USER_TASK_ERROR: 'CREATE_USER_TASK_ERROR',

  GET_TASKS_REQUESTS: 'GET_TASKS_REQUESTS',
  GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
  GET_TASKS_ERROR: 'GET_TASKS_ERROR',

  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',

  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
  UPDATE_TASK_ERROR: 'UPDATE_TASK_ERROR',


  GET_USERS_REQUEST:'GET_USERS_REQUEST',
  GET_USERS_SUCCESS:'GET_USERS_SUCCESS',
  GET_USERS_ERROR:'GET_USERS_ERROR',

  GET_USER_REQUEST:'GET_USER_REQUEST',
  GET_USER_SUCCESS:'GET_USER_SUCCESS',
  GET_USER_ERROR:'GET_USER_ERROR',

  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_ERROR: 'CREATE_USER_ERROR',


}


export default ACTION_TYPES;